@startuml
actor reader
actor manager

reader->manager:提交
activate reader
manager->图书管理系统:login()
activate manager

deactivate reader
图书管理系统->还书界面:menu()
activate 还书界面
deactivate manager
deactivate 还书界面

还书界面->borrowInfor:输入编码或扫码
activate 还书界面
activate borrowInfor
deactivate 还书界面
 deactivate borrowInfor

borrowInfor->item:getitem()
activate borrowInfor
activate item
deactivate borrowInfor
deactivate item

item->还书界面:confirm
activate 还书界面
activate item
deactivate 还书界面
deactivate item

还书界面->item:update()
activate 还书界面
activate item
deactivate 还书界面
deactivate item

还书界面->borrow:update()
activate 还书界面
activate borrow
deactivate 还书界面
deactivate borrow

borrow->还书界面:还书完成
activate borrow
activate 还书界面
@enduml